platform :ios, '26.0'

project 'iosApp.xcodeproj'

target 'iosApp' do
  use_frameworks!

  pod 'UMCommon'
  pod 'UMDevice'
  pod 'UMAPM'
end

# Xcode 27 rejects the pods' default deployment target (9.0); align all pods to 15.0+.
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
